server:
  max-http-header-size: 10000
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
app:
  jwt-secret: testsecrettrewtefwfdgwdhgfsgfdcgyfcdtzsvnbyvc242gsvdghshfdhvhcvwgedewthdgfhdsfdjsfguwzegf